### ISSUE TITLE
Error when trying to import the json dashboard

### ISSUE THREAD

**Issue by fastxl** [molu8bits/squid-filebeat-kibana#8]
I get a "Sorry, there was an error" Saved objects file format is invalid and cannot be imported. Any suggestions?

**Comment by molu8bits** [comment]
Probably version of the software. Current version was tested with 7.8 and should work with this version and newer.

**Comment by francescouk** [comment]
I´m also having the same problem. Tried on elk stak 7.8 - 7.91 and none of them are working
![2020-09-06 16_02_08-Elastic](https://user-images.githubusercontent.com/1994892/92333273-97a33580-f05a-11ea-83e0-88b13ec74756.png)
![2020-09-06 16_05_11-Window](https://user-images.githubusercontent.com/1994892/92333312-d638f000-f05a-11ea-9f4d-e9da69804036.png)

**Comment by molu8bits** [comment]
Yes, there was a problem with that. Probably that json comes from api export which seems to be not compatible with GUI.
I have tested and added *.ndjson version which can get be imported without any issue for ELK 7.8/7.9

**Comment by francescouk** [comment]
@molu8bits thanks to update the dashboard! Really appreciate! 

Also, if you don't mind, what's the chance to help to get the internal IP enriched on the geoip? Eg 192.168.0.1

**Comment by molu8bits** [comment]
Yeah I tried to some time ago. The problem is that you must keep your own copy of GeoIP database (mmdb) and add records to it. 
Library which writes to MMDB file is for Perl only. I found that work needed to implement such thing  into my monitoring stacks just wasn't worth my time. Also the monitoring solution would be more complicated and I prefer simplicity.

Anyway if you want to build and maitenance your own maxmind db check details here:
https://blog.maxmind.com/2015/09/29/building-your-own-mmdb-database-for-fun-and-profit/
